### ISSUE TITLE
Messages not appearing on other servers

### ISSUE THREAD

**Issue by sephallen** [tsebring/ArkCrossServerChat#1]
I have your fork of the Beyond API and your cross server chat plugin running on two of my ARK servers on my Windows Server 2016 VM.
(I had to install the Visual C++ Redistributable for Visual Studio 2015 in order to get it to run first).
Beyond loads fine without errors and it also says the ArkCrossServerChat plugin has loaded.
I have checked the db file, it has been successfully created and updated, but the chat is not showing across the two servers.

**Comment by tsebring** [comment]
Are both servers configured? In **/ArkCrossServerChat/config.json** the two settings
`ServerKey`: Must be unique per server.
`ClusterKey`: Should be same for both servers.

If the configuration is correct, the database gets updated, both ARK servers are hosted on the same machine and have [Synchronization Object Security and Access Rights](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686670(v=vs.85).aspx), then it is quite odd.

Are you running the ARK Servers as administrator?

---

The only thing I can think of is that it might be a problem with the synchronization object. The plugin uses the Windows PulseEvent Synchronization API, and it is possible there are access restrictions in your OS preventing it.

If you want to investigate the synchronization object, you can download Process Explorer and follow this guide:
https://stackoverflow.com/a/801433

The event name is `ArkCrossServerChat_{ClusterKey}`.

**Comment by sephallen** [comment]
I fired up Process Explorer and found out only one of the servers had ArkCrossServerChat event running on it. I redid all my steps and I now have cross server chat working great.

Thanks for the help and thanks for all your hard work!
You might want to consider taking donations!
