### ISSUE TITLE
Investigate adding map name in chat

### ISSUE THREAD

**Issue by tsebring** [tsebring/ArkCrossServerChat#2]
Option to show the map name in chat to tell which server players are currently on.

**Comment by Toma-vllbrig31** [comment]
Perhaps you could look into https://github.com/Toma-vllbrig31/ArkCrossServerChat/commit/1a42f9ec4a6cce656e9a3468558c98a1bdf8afda.

**Comment by tsebring** [comment]
It will be added in the 2.0 version. I'll take a look and get some ideas from your code. Thanks!

**Comment by tsebring** [comment]
Implemented in latest source. Requires new ARK Server API release.
