### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Nackenschelle** [tsebring/ArkCrossServerChat#4]
what do i need to add here?

	"ServerKey": "server1",

**Comment by Toma-vllbrig31** [comment]
A unique Serverkey for the Server: e.g. "TheIsland", or leave it at "server1". For your second server in the cluster you have to rename it to "server2" and so on.

**Comment by Nackenschelle** [comment]
thanks in advance <3

#closerequest

**Comment by StiGMaT14** [comment]
Hi im having an issue with this config. my server all 6 maps run off the same game installation hense off the same plugin folder and config... all my maps would have the same server key. how can i get around this? i tried loading your repo in visual studio 2017... i made a fix to the config loading... but i cant compile im getting this error:

'/ZI' and '/GL' not compatibles

i followed https://arkserverapi.com/threads/tutorial-create-plugins.55/#lg=_xfUid-2-1593182867&slide=0 tutorial by OwnProx

i had a hard time finding the the additinal libaries.. i think i got the right ones

here i added a screenshot of how i though to fix my issue... can you help me compile this i might want to play around with it.

<img width="975" alt="mysolution" src="https://user-images.githubusercontent.com/67499078/85924463-7656e980-b860-11ea-836c-ebf94a6a9a6e.png">
